#!/bin/bash

HOST="localhost"
# PORT="9500"
PORT=$WEBSCAN_PORT

# Первый параметр передаваемый скрипту
# метод вызываемый на сервере
if ! [[ -z $1 ]] ; then METHOD=$1
else METHOD="ping"
fi

# Второй параметр данные которые необходимо
# передать на сервер в качестве параметров метода

# Генерируем случайное число для id
# Передача id обязатальна, так как без него сервер не отвечает
#
ID=$((1 + RANDOM % 20))

# Формируем JSON
#
JSON=$(\
printf "{\n"
printf "\t\"jsonrpc\": \"2.0\",\n"
printf "\t\"method\": \"$METHOD\",\n"
if ! [ -z $2 ] ; then
printf "\t\"params\": [\"$2\"],\n"
fi
printf "\t\"id\": \"$ID\"\n"
printf "}\n")

# Отправляем JSON на JSON RPC сервер
#
echo "############### REQUEST ################"
echo $JSON "-> $HOST:$PORT"
echo "############### RESPONSE ###############"
curl -s -H "Content-Type: application/json" \
    -X POST http://$HOST:$PORT --data "$JSON" | jq '.'
echo "############## ### END ### ##############"
